name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: rscohn2/oneapi-spec:latest
    steps:
    - uses: nelonoel/branch-name@v1
    - uses: actions/checkout@v2
    - name: Build
      run: |
          apt-get update -qq
          DEBIAN_FRONTEND=noninteractive xargs -a packages.txt apt-get install -qq
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade --quiet -r requirements.txt
          python doc.py html
          python doc.py latexpdf
          python doc.py spelling
          mkdir -p public/${BRANCH_NAME}
          rm -rf public/${BRANCH_NAME}/*
          cp -r build/html/* public/${BRANCH_NAME}
    - name: Archive build
      uses: actions/upload-artifact@v1
      with:
          name: build
          path: build
    - name: Publish
      uses: peaceiris/actions-gh-pages@v3.7.0-6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: public
        keep_files: true
